[project]
name = "sample-alembic-app"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Jerzy Boksa", email = "jerzyxboksa@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.1",
    "fastapi>=0.141.1",
    "psycopg2-binary>=2.9.12",
    "sqlalchemy>=2.0.51",
    "uvicorn>=0.52.1",
]

[project.scripts]
sample-alembic-app = "sample_alembic_app:main"

